# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b1f393d9ed96f9e633b229fc8947687dd73fd0d1b1e0aa30b4b5a17fd8f3f62d1ff6bdb1cb883728a70fdd9b3505777162d2a19f5fa64a9b51e8ceb8a0667a9

test:
  secret_key_base: 7b91d8e72916c199c6950d21c35a75045ac7bc51a3b4403c13a4f02c35ab168ca2c2be95312d45b175adfa8052e6b6bbdbeed1388b098cb2314835883f96966e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
